export const siteConfig = {
  name: "La Vanilla Supplier",
  description: "Premium Indonesian vanilla supplier for wholesale, B2B, and direct export. HACCP certified. 10+ years experience shipping to 20+ countries.",
  url: "https://lavanillasupplier.com",
  ogImage: "/og-image.jpg",
  keywords: [
    "vanilla supplier Indonesia",
    "wholesale vanilla beans",
    "vanilla paste manufacturer",
    "vanilla powder supplier",
    "B2B vanilla exporter",
    "HACCP certified vanilla",
    "premium vanilla beans",
    "vanilla extract supplier",
    "organic vanilla Indonesia",
    "bulk vanilla supplier",
  ],
  social: {
    whatsapp: "+6287834756945",
    email: "admin@lavanillasupplier.com",
  },
  regions: ["UAE", "Australia", "USA", "Europe"] as const,
  products: [
    {
      id: "vanilla-beans",
      name: "Vanilla Beans",
      slug: "vanilla-beans",
      shortDescription: "Premium Grade A & Grade B vanilla beans, hand-picked and sun-cured for 6-9 months.",
      description: "Our vanilla beans are sourced directly from Indonesian smallholder farmers and carefully cured using traditional methods. Each bean is hand-picked at peak maturity and sun-dried for 6-9 months to develop optimal vanillin content (1.3-2.7%). Available in Grade A Gourmet and Grade B Extraction grades.",
      category: "beans" as const,
      image: "/images/vanilla-beans.jpg",
      specifications: {
        species: "V. planifolia",
        moistureContent: "25-35%",
        vanillinContent: "1.3-2.7%",
        beanLength: "16-20 cm (Grade A) / 10-16 cm (Grade B)",
        curing: "6-9 months, sun-dried + sweat-box",
        moq: "25 kg",
        hsCode: "0905.10",
        incoterms: "EXW / FOB Jakarta / CIF / DDP",
      },
      certifications: ["HACCP", "Halal", "Phytosanitary"],
    },
    {
      id: "vanilla-paste",
      name: "Vanilla Paste",
      slug: "vanilla-paste",
      shortDescription: "Custom composition vanilla paste tailored to your exact specifications.",
      description: "Our vanilla paste is manufactured to your exact requirements. We offer custom formulations with adjustable vanillin concentration, sugar content, and viscosity. Perfect for food manufacturers, bakeries, and beverage companies requiring consistent, high-quality vanilla flavoring.",
      category: "paste" as const,
      image: "/images/vanilla-paste.jpg",
      specifications: {
        vanillinContent: "Custom (1.3-2.7%)",
        sugarContent: "Custom (0-65%)",
        viscosity: "Adjustable",
        shelfLife: "24 months",
        packaging: "Bulk drums / Retail bottles",
        moq: "25 kg",
        hsCode: "2106.90",
        incoterms: "EXW / FOB Jakarta / CIF / DDP",
      },
      certifications: ["HACCP", "Halal", "FDA Compliant"],
    },
    {
      id: "vanilla-powder",
      name: "Vanilla Powder",
      slug: "vanilla-powder",
      shortDescription: "100% pure vanilla powder, finely ground from premium cured beans.",
      description: "Our vanilla powder is made from 100% pure cured vanilla beans, finely ground to a consistent mesh size. No fillers, no additives. Ideal for dry mixes, baking blends, and applications where liquid vanilla is not suitable.",
      category: "powder" as const,
      image: "/images/vanilla-powder.jpg",
      specifications: {
        meshSize: "40-80 mesh (customizable)",
        vanillinContent: "1.3-2.7%",
        moisture: "< 5%",
        purity: "100% pure vanilla",
        packaging: "Bulk bags / Retail containers",
        moq: "25 kg",
        hsCode: "0905.20",
        incoterms: "EXW / FOB Jakarta / CIF / DDP",
      },
      certifications: ["HACCP", "Halal", "Organic"],
    },
  ],
  stats: {
    countriesServed: "20+",
    yearsExperience: "10+",
    happyClients: "30+",
    tonsExported: "500+",
  },
} as const;

export type Product = (typeof siteConfig.products)[number];
